services:

  # mariadb container ------------------------------------------------------------

  # this is the only container that no depend on the others, so its the first to be created
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env

  # wordpress container ------------------------------------------------------------

  # this is the second container to be created, it depends on the mariadb container
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  # nginx container ------------------------------------------------------------

  # this is the last container to be created, it depends on the wordpress container
  # in the build moment with show the private informations that where in the .env file
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - '443:443'
      - '8080:8080'
    volumes:
      - wordpress_files:/var/www/inception/
      - ./static_site:/var/www/static_site:ro
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

  # redis container ------------------------------------------------------------

  # this is the first container from bonus, it depends on the wordpress container
  redis:
    container_name: redis
    build: ./requirements/redis/
    volumes:
      - redis_data:/data
    networks:
      - all
    init: true
    restart: on-failure
    depends_on:
      - wordpress

 
  # ftp container ------------------------------------------------------------

  ftp:
    container_name: ftp
    build: ./requirements/ftp/
    volumes:
      - wordpress_files:/home/ftpuser
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - all
    environment:
      FTP_USER: ftpuser
      FTP_PASS: ftppass
    restart: on-failure
    depends_on:
      - wordpress

   # adminer service ------------------------------------------------------------

  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    networks:
      - all
    ports:
      - "8081:80"      # Host port 8081, container port 80
    depends_on:
      - mariadb
    restart: on-failure


# volumes --------------------------------------------------------------------

# keeps the data shared between the containers
# it acts like a shared hard drive between the containers and the host machine
# device: where the data will be stored in the host machine
volumes:

  # keeps the database
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  # keeps the wordpress files
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files
      
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/redis_data

# networks --------------------------------------------------------------------

# this network is used to connect the containers
# it acts like a virtual switch between the containers
# all is the name of the network
# bridge is the type of the network
networks:
  all:
    driver: bridge
